### ISSUE TITLE
Problem with JQuery 3.2.1

### ISSUE THREAD

**Issue by mhyeganeh** [sms1989/persian-numbers-jquery-plugin#1]
Hi,

First of all thank you for your effort. It's working great with old version of Jquery (v1) but as far as I found out it's not working with JQuery v3.2.1. Do you have any idea about the problem and solution...?

Thanks in advance.

**Comment by sms1989** [comment]
@mhyeganeh 
Thanks for your issue.

**Comment by sms1989** [comment]
@mhyeganeh
Thanks for your issue.

**Comment by mhyeganeh** [comment]
I found the solution! It needs to download jquery-migrate-3.0.1 form [here ](http://jquery.com/download/)and import it to the project right after importing jquery-3.2.1 and it's going well.

`<script src="/path/to/plugin/jquery-3.2.1.min.js" type="text/javascript"></script>`
`<script src="/path/to/plugin/jquery-migrate-3.0.1.min.js" type="text/javascript"></script>`

**Comment by sms1989** [comment]
@mhyeganeh 

it's fixed in new version without jquery migrate. jquery migrate just added an overhead
